deployment:
  tasks:
    - export DEPLOYPATH=/home/deloprosit/public_html
    - export BACKENDPATH=$DEPLOYPATH/api
    - export FRONTENDPATH=$DEPLOYPATH/client

    # Build and deploy ASP.NET Core backend
    - cd .
    - dotnet publish -c Release -o $BACKENDPATH
    - cp -r $BACKENDPATH/wwwroot/* $DEPLOYPATH/

    # Build and deploy Vue.js frontend
    - cd deloprosit.client
    - npm install
    - npm run build
    - cp -r dist/* $FRONTENDPATH/

    # Set permissions
    - chmod -R 755 $DEPLOYPATH
    - chown -R deloprosit:deloprosit $DEPLOYPATH