# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - deloprosit

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Create appsettings.Production.json with secrets
        shell: pwsh
        run: |
          @"
          {
            `"Logging`": {
              `"LogLevel`": {
              `"Default`": `"Information`",
              `"Microsoft.AspNetCore`": `"Warning`"
              }
            },
            `"ClientUrl`": `"https://deloprosit.azurewebsites.net`",
            `"CorsOrigins`": [
              `"https://deloprosit.azurewebsites.net`"
            ],
            `"GoogleSecrets`": `"$($env:GOOGLESECRETS)`",
            `"GoogleDrive`": `"$($env:GOOGLEDRIVE)`",
          }
          "@ | Out-File -FilePath appsettings.Production.json -Encoding utf8

          Get-Content appsettings.Production.json
          
      - name: Build with dotnet
        run: dotnet build Deloprosit.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish Deloprosit.sln -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CFD26732ABEF4EBDBF0287101082B537 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F55EBF40BF9C4CC197BE51CA902E78E3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A039E8C3F5FA4D7E8F5A5B04FDEC9205 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'deloprosit'
          slot-name: 'Production'
          package: .
          
